version: "3.8"

services:
  django:
    image: my-django-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/admin/GSP_Backend:/app
    deploy:
      placement:
        constraints:
          - "node.role==manager"
