# Generated by Django 5.1.6 on 2025-02-23 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="admin",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
