# Generated by Django 5.1.6 on 2025-02-23 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seat_admin", "0002_admin_created_at_admin_is_active_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
