# Generated by Django 5.1.6 on 2025-02-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="billing",
            name="selected_courses",
            field=models.JSONField(
                help_text="\n        Format: [\n            {\n                'courseName': str,\n                'branch': str, \n                'selectedSeats': int,\n                'pricePerSeat': decimal,\n                'totalPrice': decimal\n            }\n        ]\n    "
            ),
        ),
    ]
