# Generated by Django 5.1.6 on 2025-02-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0002_billing_is_verified_alter_billing_selected_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locked_courses",
            field=models.JSONField(default=list),
        ),
    ]
