# Generated by Django 5.1.6 on 2025-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0003_user_locked_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="institute_type",
            field=models.CharField(default="Engineering College", max_length=255),
        ),
    ]
