# Generated by Django 5.1.6 on 2025-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0004_course_institute_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="institute_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="institute_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
