# Generated by Django 5.1.6 on 2025-02-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0005_alter_course_city_alter_course_institute_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
