# Generated by Django 5.1.6 on 2025-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seat_users", "0006_user_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
